name: Build Job
on:
  schedule:
    - cron:  '15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: checkout code.
    - name: Create build
      run: |
        apt-get update && apt-get install git -y
        docker build --build-arg VERSION=$(git ls-remote --tags https://git.sr.ht/~kennylevinsen/greetd | tail -n 1 | grep -o -E '[0-9]\.[0-9]\.[0-9]') --build-arg TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} .
