name: Release Builder
on:
  workflow_dispatch:
    inputs:
      vTag:
          description: 'Version Tag'     
          required: false
          default: ''
  repository_dispatch:
jobs:
  release-build:
    env:
      tag: ""
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Code Checkout.
    - name: Determine version
      run: |
        if [[ $vTag == "" ]]; then
          tag=$(git ls-remote --tags https://git.sr.ht/~kennylevinsen/greetd | tail -n 1 | grep -o -E '[0-9]\.[0-9]\.[0-9]')
        else
          tag=$vTag
        fi
        echo "Tag to be used is $tag"
        echo "tag=$tag" >> $GITHUB_ENV
    - name: Build and Release artifacts
      run: |
        docker build --build-arg VERSION=${{ env.tag }} --build-arg TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} .

