name: Release Tracker
# Triggers on cron job expression: 00:00 UTC on the 1, 16 and 31th of every month
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1/15 * *'
jobs:
  release-check:
    env:
      VERSION: "0.0.0"
      IS_RELEASE_CREATED: false
    runs-on: ubuntu-latest
    steps:
    - name: Check for New Release
      run: |
        echo "Steps to check if new release is created"
        BUILDER_TAGS=$(git ls-remote --tags https://github.com/arush-sal/tuigreet-greetd-dpkg-builder | awk '{print $2}' | sed 's|refs/tags/||' | grep -v -E '\^\{\}')
        GREETD_TAGS=$(git ls-remote --tags https://git.sr.ht/~kennylevinsen/greetd | awk '{print $2}' | sed 's|refs/tags/||' | grep -v -E '\^\{\}')
        NEW_TAGS=$(comm -23 <(echo "$GREETD_TAGS" | sort) <(echo "$BUILDER_TAGS" | sort))

        if [[ -n $NEW_TAGS ]]; then
          echo "There is a new release. Release Builder will be triggered."
          echo "VERSION=$NEW_TAGS"
          echo "VERSION=$NEW_TAGS" >> $GITHUB_ENV
          # set the env to true if release is created.
          echo 'IS_RELEASE_CREATED=true' >> $GITHUB_ENV
        fi

    - name: Clone and update mirror
      if: env.IS_RELEASE_CREATED == 'true'
      run: |
        git clone --bare https://git.sr.ht/~kennylevinsen/greetd
        cd ./greetd.git
        git push --mirror https://arush-sal:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/arush-sal/greetd

    - name: Trigger Release build
      if: env.IS_RELEASE_CREATED == 'true'
      run: |
        for TAG in $(echo ${{ env.VERSION }}); do
          curl -X POST \
                -u "arush-sal:${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
                -H "Accept: application/vnd.github.everest-preview+json" \
                -H "Content-Type: application/json" https://api.github.com/repos/arush-sal/tuigreet-greetd-dpkg-builder/dispatches \
                --data "{\"event_type\": \"release_$TAG\"}"
        done
