name: Release Builder
on:
  workflow_dispatch:
    inputs:
      vTag:
          description: 'Version Tag'
          required: false
          default: ''
  repository_dispatch:
jobs:
  release-build:
    env:
      tag: ""
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Code Checkout.
    - name: Determine version
      run: |
        if [[ "${{ github.event.inputs.vTag }}" == "" ]]; then
          tag=$(git ls-remote --tags https://git.sr.ht/~kennylevinsen/greetd | tail -n 1 | grep -o -E '[0-9]\.[0-9]\.[0-9]')
        else
          tag="${{ github.event.inputs.vTag }}"
        fi
        echo "Tag to be used is $tag"
        echo "tag=$tag" >> $GITHUB_ENV
    - name: Build and extract artifact
      run: |
        docker build -v $(pwd):/build --build-arg VERSION=${{ env.tag }} -t tuigreet .
        container_id=$(docker create tuigreet)
        docker cp "$container_id:/tuigreet-greetd_${{ env.tag }}.deb" "$()/tuigreet-greetd_${{ env.tag }}.deb"
        docker rm "$container_id"
        ls
