name: Release Builder
on:
  workflow_dispatch:
    inputs:
      vTag:
          description: 'Version Tag'
          required: false
          default: ''
  repository_dispatch:
jobs:
  release-build:
    env:
      tag: ""
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
      name: Code Checkout.
    - name: Determine version
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        if [[ "${{ github.event.inputs.vTag }}" == "" ]]; then
          tag=$(git ls-remote --tags https://git.sr.ht/~kennylevinsen/greetd | tail -n 1 | grep -o -E '[0-9]\.[0-9]\.[0-9]')
        else
          tag="${{ github.event.inputs.vTag }}"
        fi
        echo "Tag to be used is $tag"
        echo "tag=$tag" >> $GITHUB_ENV
    - name: Determine version
      if: ${{ github.event_name == 'repository_dispatch' }}
      run: |
        tag="${{ github.event.client_payload.tag }}"
        echo "Tag to be used is $tag"
        echo "tag=$tag" >> $GITHUB_ENV
    - name: Build artifact
      run: |
        docker build --build-arg VERSION=${{ env.tag }} -t tuigreet .
        container_id=$(docker create tuigreet)
        docker cp "$container_id:/tuigreet-greetd_${{ env.tag }}.deb" "$(pwd)/tuigreet-greetd_${{ env.tag }}.deb"
        docker rm "$container_id"
        ls
    - name: Extract artifact
      run: |
        echo "Created artifact tuigreet docker contianer"
        container_id=$(docker create tuigreet)
        echo "Extract artifact from container"
        docker cp "$container_id:/tuigreet-greetd_${{ env.tag }}.deb" "$(pwd)/tuigreet-greetd_${{ env.tag }}.deb"
        echo "Remove container"
        docker rm "$container_id"
    - name: Release artifact
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.tag }}
        files: tuigreet-greetd_${{ env.tag }}.deb
